### ISSUE TITLE
Why alphafold-multistate only generate 2 models

### ISSUE THREAD

**Issue by yazdan12555** [huhlim/alphafold-multistate#13]
@huhlim 
Hi,
I have a general question: why does AlphaFold-MultiState only generate two models?

I attempted to increase the number of models in the Google Colab version, but the third model turned out to be an artifact. While increasing the number of seeds might seem like a potential solution, I’m uncertain if doing so could address the loss of the three models that AlphaFold-MultiState skips compared to AlphaFold2.

**Comment by huhlim** [comment]
The method is based on AlphaFold2 and force to use template information for the modeling by removing contributions of MSA. There are five ML models for AlphaFold2, and only two of them uses template information. Consequently, the two models are relevant, while the other three ML models are not because they do not use template information.
