### ISSUE TITLE
query_align = next(iter(sequence_dict.values())) && StopIteration

### ISSUE THREAD

**Issue by jixing475** [huhlim/alphafold-multistate#6]
Hello, I encountered an error during the configuration and usage process. 

I was able to run the original version of AlphaFold successfully after configuring the environment. 

However, when attempting to predict the GPCR state, I encountered an error. 

```
query_align = next(iter(sequence_dict.values()))
StopIteration
```

![image](https://user-images.githubusercontent.com/10696315/223010843-34213f89-6efd-4126-a3f1-207435432934.png)

Additionally, the following files were generated but were empty: "uniref90_hits.sto" and "mgnify_hits.sto".

**Comment by huhlim** [comment]
As far as I understood, you tried to run our scripts locally, and running the original AF protocol using our scripts was successful. If so, it is strange because our protocol runs the exactly same input preparation procedure and modifies MSA features afterward before running AF2's model. So, can you try it again and check if the error is persistent?

**Comment by jixing475** [comment]
Hi, 

I noticed that the two generated files in the red box appear to be empty(In the below screenshot). Could it be possible that the MSA comparison was not done by default?

![](https://user-images.githubusercontent.com/10696315/224886372-9d29e9db-23c7-438c-8ee5-f017f38e7599.png)


Furthermore, I would like to bring to your attention that I may have misrepresented this error by failing to predict the state accurately.  running the original AF protocol using your scripts, i get the same error information. 

Lastly, I have attached the PBS script that I ran for your reference. 

![image](https://user-images.githubusercontent.com/10696315/224887410-d8bb543d-a82c-456c-ab17-c1bb1a270a68.png)


Please let me know if you require any further information.

Best regards, Thanks

**Comment by huhlim** [comment]
It seems like there were empty ".sto" files in the directory before running the AF script. AF2 attempts to reuse those files by default. You need to remove the directory and try it again. The image is log messages when I run the script. 
![image](https://user-images.githubusercontent.com/13167164/225049074-9e72a142-aed8-420c-8d07-8c3750d81174.png)
If the error persists, you can check if jackhmmer and related databases (uniref90.fasta and mgy_clusters.fa) are configured correctly.

**Comment by jixing475** [comment]
Subject: **Assistance with AlphaFold Query and Script Issues**

Hello, Thank you for your prompt response.

I have thoroughly inspected the input files and data files, and have deleted the previously generated .sto files. After rerunning the script, I discovered an issue with the query step in the program. The query time seems to be too short, as evidenced in the attached screenshot.


![](https://files.mdnice.com/user/2805/3a9111c7-18ce-4800-a6c7-e49d5f483209.png)


I have made a comparison between the jackhmmer.py script provided by the official AlphaFold and the one I am currently using (specifically, the Multi-state GPCR version). As shown in the screenshots below, there are two notable differences. The left image represents the official script, while the right image represents the one I am currently utilizing. Can you please confirm if this is normal?


![](https://files.mdnice.com/user/2805/bacb2218-8d49-4de4-ae4e-a173688e5485.png)



Additionally, I have scrutinized the input CXCR2.fasta file from the following perspectives and found no issues:

1. Short input sequence
2. Presence of non-standard amino acids
3. Formatting issues

Thank you for your assistance. Should you require any further information, please do not hesitate to contact me(/jixing475@163.com).

**Comment by huhlim** [comment]
I found something strange from your log message that `jackhmmer.py` is called instead of an executable binary file `jackhmmer`. I suspect that you might not have installed the HMMER package or incorrectly configured it. In [libconfig_af.py](https://github.com/huhlim/alphafold-multistate/blob/main/structure_prediction/libconfig_af.py), __binary_paths__ should be directed to __executable binary__ files rather than scripts in `alphafold/data/tools` directory.
You may refer to an [issue](https://github.com/deepmind/alphafold/issues/24) or [our AF2 local installation script](https://github.com/huhlim/alphafold-multistate/blob/main/structure_prediction/conda_create.sh). 

I updated the [installation script](https://github.com/huhlim/alphafold-multistate/blob/main/structure_prediction/conda_create.sh) and added a missing file, `requirements.txt`, which reflect version updates in dependent libraries such as `jax`, `jaxlib`, `dm-tree`, `haiku`, and etc. Consequently, I also updated the version of `alphafold`. 
I think the difference in `jackhmmer.py` is okay because the difference originated from a recent (Dec. 15, 2022) [commit](https://github.com/deepmind/alphafold/commit/ed3ecabff525c983bdef8023dd56cf45526b5001), and my scripts are based on a version of AF2 before May, 2022. But, it was also updated as I updated the version of `alphafold`.

**Comment by jixing475** [comment]
@huhlim 

Hello, I wanted to express my gratitude for your invaluable assistance in resolving the issues I was experiencing.

The problem has been successfully resolved. As it turns out, it was indeed a problem with the binary file. However, through reset the environment and adjusting the binary path, I was able to run it successfully.

Once again, I would like to extend my heartfelt appreciation for your support. 


![](https://files.mdnice.com/user/2805/72f02879-2b4f-4c2c-8022-03d26e706b1c.png)

**Comment by huhlim** [comment]
I am glad that the issue is resolved! I hope you find our work helpful :)
